### PR TITLE
[feature] Add profile image to each user

### PR DESCRIPTION
**Pull request by csungwon**
Each user can upload a profile picture from their local disk. In the development
environment the images are saved in the local disk. In the production environment
we use Amazon's S3 storage to store images. Paperclip gem was used to implement
image attributes to users. The default images (for users without profile image)
were also added to app/assets/images.

### CODE REVIEW

**Review by kyriakipapadimitriou — APPROVED** [review]
Concise implementation of the user profile with profile icons for both the user view as well as the identity of the user when they comment. From my understanding of the tests users can update their profile and add picture. For future features, teams could implement adding picture while creating the user for the first time but that should be discussed with the client. Everything looks great!

**Review by Jldeatrick — APPROVED** [review]
Amazing Job! And super precise testing to go along with it! Really excited about this

**Review by kimhoang73 — APPROVED** [review]
so cool that you got it to work with S3! overall looks clean and concise. I agree with sandy, future devs can talk to client to see if they want a profile pic upon creation of new user. i actually think it's more common to just keep the default pic until you decide you want to upload your own later.. but it will be up to the future haha

**Review by julies642 — APPROVED** [review]
Nice work! As everyone else said, great testing. Great job figuring this out, it will probably be great for users interacting on the app.

**Pull request merged**
